<a href="https://colab.research.google.com/github/PriyaKsagar2/Machine-Learning/blob/main/AINN_exp_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Priya Kishor Kshirsagar
#2019BEC134
#B59

In [ ]:
#Experiment 8

In [ ]:
import numpy as np

In [ ]:

def Bipolar_Sigmoid(val):
    return (2/(1+np.exp(-val)))-1

def linear(val):
    return val

def d_bipolar_sigmoid(val):
    return 1/2*(1-val**2)

def d_linear(val):
    return 1


#Given data
X1,X2,X3,X4=[0,0,1],[0,1,1],[1,0,1],[1,1,1]
X =np.vstack((X1,X2,X3,X4))
d1,d2,d3,d4=0,1,1,0
D=np.vstack((d1,d2,d3,d4))
W=[1,-1,-1]
V=np.array([[1,-1,1],[1,2,1]])

In [ ]:
# Case-1
activation1=Bipolar_Sigmoid
activation2=linear
dw=d_linear
dv=d_bipolar_sigmoid

def solver(X,d,W,V,activation1,activation2,E,c,d1,d2):
    net1=np.dot(V,X)
    o1=activation1(net1)
    
    arr=[1]
    o1=np.append(o1,arr)
    net2=np.dot(W,o1)
    o2=activation2(net2)
    E=E+(d-o2)

    dw=c*(d-o2)*d1(o2)
    W=W+dw*o1.T
    dv0=c*(dw*W[0]*d2(o1[0]))
    dv1=c*(dw*W[1]*d2(o1[1]))
    dv=np.vstack((dv0,dv1))
    V=V+dv*X.T    
    return E,W,V

E_prev=0
E_min=0.5
c= 0.2
iteration= 0

while(True):
    E_prev=0
    for i in range(4):
        E_prev,W,V=solver(X[i],D[i],W,V,activation1,activation2,E_prev,c,dw,dv)
    iteration=iteration+1
    if(E_prev<=E_min ):
        break

print(V)
print(W)
print(iteration)

[[ 0.96551764 -0.86475264  1.12937531]
 [ 0.99871866  1.99646088  0.98247773]]
[ 0.84359399 -0.00672547  0.04826806]
1


In [ ]:
#case 2:
activation1=Bipolar_Sigmoid
activation2=Bipolar_Sigmoid
dw=d_bipolar_sigmoid
dv=d_bipolar_sigmoid
E_prev=0
E_min=0.5
c=0.2
iteration=0
while(True):
    E_prev=0
    
    for i in range(4):
        E_prev,W,V=solver(X[i],D[i],W,V,activation1,activation2,E_prev,c,dw,dv)
    iteration=iteration+1
    if(E_prev<=E_min ):
        break
print("Final V={}",V)
print("W={}",W)
print("Iteration number= {}",iteration)

Final V={} [[ 0.96389647 -0.84951046  1.14421475]
 [ 0.99953175  1.99696617  0.9834871 ]]
W={} [0.88380344 0.18812828 0.25262168]
Iteration number= {} 3


In [ ]:
#Case 3 :
activation1=linear
activation2=Bipolar_Sigmoid
dw=d_bipolar_sigmoid
dv=d_linear
E_prev=0
E_min=0.5
c=0.2
iteration=0
while(True):
    E_prev=0
    for i in range(4):
        E_prev,W,V=solver(X[i],D[i],W,V,activation1,activation2,E_prev,c,dw,dv)
    iteration=iteration+1
    if(E_prev<=E_min ):
        break
print("Final V={}",V)
print("W={}",W)
print("Iteration number= {}",iteration)

Final V={} [[ 0.96063004 -0.84528072  1.14259981]
 [ 0.99877857  1.99876808  0.98433637]]
W={} [0.83143816 0.2059642  0.24192512]
Iteration number= {} 1
